version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack-pritika
      #- run: return 1
      #- run:
      #    name: Destroy environment
      #    command: |
      #      aws cloudformation delete-stack --stack-name my-stack-pritika
      #    when: on_fail
  populate_inventory:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text >> inventory         
           
workflows:
  my_workflow:
    jobs:
      - create_infrastructure